### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by TheSemicolon**
Adding a target for Seq (https://getseq.net/) as that is our log repository (rather than ES and Kibana). I am also adding support for the use of an SMTP port and SSL for the Email target.

### CODE REVIEW

**Comment by TheSemicolon** [comment]
This is my first contribution to any project, so if I am terrible, please let me know so that I can "fix" myself. And I can't push my changes in the dev branch up, so I am not too sure what I need to do to get the code up for review.

**Comment by TheSemicolon** [comment]
I have forked and added my changes so that you can take a look.

**Comment by EsOsO** [comment]
Hi @TheSemicolon, I will look asap into the issue, basically you need to checkout the dev branch from my repo, commit the changes and push back to origin.

**Comment by TheSemicolon** [comment]
I am getting permission denied trying to push my changes back up.

**Comment by EsOsO** [comment]
you need to push back to dev branch, not master

**Pull request closed without merging**
